//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaRankings.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FifaRankingsEntities : DbContext
    {
        public FifaRankingsEntities()
            : base("name=FifaRankingsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MatchResultLog> MatchResultLogs { get; set; }
        public virtual DbSet<MatchStatu> MatchStatus { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<RankingScoreLog> RankingScoreLogs { get; set; }
        public virtual DbSet<ResultOption> ResultOptions { get; set; }
        public virtual DbSet<MatchResult> MatchResults { get; set; }
        public virtual DbSet<RankingPoint> RankingPoints { get; set; }
        public virtual DbSet<HandicapsRounded> HandicapsRoundeds { get; set; }
        public virtual DbSet<HandicapThreshold> HandicapThresholds { get; set; }
        public virtual DbSet<RankingLeaderboard> RankingLeaderboards { get; set; }
        public virtual DbSet<Handicap> Handicaps { get; set; }
    }
}
