//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaRankings.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandicapThreshold
    {
        public int Id { get; set; }
        public string Stars { get; set; }
        public decimal Low { get; set; }
        public decimal High { get; set; }
    }
}
