//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaRankings.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResult
    {
        public System.DateTime MatchDate { get; set; }
        public string MatchType { get; set; }
        public string HomePlayer { get; set; }
        public string HomeScore { get; set; }
        public string AwayScore { get; set; }
        public string AwayPlayer { get; set; }
        public string PenaltiesPlayed { get; set; }
    }
}
