//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaRankings.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.MatchResultLogs = new HashSet<MatchResultLog>();
            this.MatchResultLogs1 = new HashSet<MatchResultLog>();
            this.RankingScoreLogs = new HashSet<RankingScoreLog>();
            this.RankingScoreLogs1 = new HashSet<RankingScoreLog>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<MatchResultLog> MatchResultLogs { get; set; }
        public virtual ICollection<MatchResultLog> MatchResultLogs1 { get; set; }
        public virtual ICollection<RankingScoreLog> RankingScoreLogs { get; set; }
        public virtual ICollection<RankingScoreLog> RankingScoreLogs1 { get; set; }
    }
}
