//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaRankings.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultOption
    {
        public ResultOption()
        {
            this.RankingScoreLogs = new HashSet<RankingScoreLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Points { get; set; }
    
        public virtual ICollection<RankingScoreLog> RankingScoreLogs { get; set; }
    }
}
