//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaRankings
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FifaRankingsContext : DbContext
    {
        public FifaRankingsContext()
            : base("name=FifaRankingsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MatchResultLog> MatchResultLogs { get; set; }
        public virtual DbSet<MatchStatu> MatchStatus { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<RankingScoreLog> RankingScoreLogs { get; set; }
        public virtual DbSet<ResultOption> ResultOptions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<RankingLeaderboard> RankingLeaderboards { get; set; }
    }
}
