//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaRankings
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchStatu
    {
        public MatchStatu()
        {
            this.MatchResultLogs = new HashSet<MatchResultLog>();
            this.RankingScoreLogs = new HashSet<RankingScoreLog>();
        }
    
        public int Id { get; set; }
        public string StatusName { get; set; }
        public decimal Multiplier { get; set; }
    
        public virtual ICollection<MatchResultLog> MatchResultLogs { get; set; }
        public virtual ICollection<RankingScoreLog> RankingScoreLogs { get; set; }
    }
}
