//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaRankings
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResultLog
    {
        public MatchResultLog()
        {
            this.RankingScoreLogs = new HashSet<RankingScoreLog>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int MatchStatusId { get; set; }
        public int HomePlayerId { get; set; }
        public int HomeScore { get; set; }
        public int AwayPlayerId { get; set; }
        public int AwayScore { get; set; }
        public bool Penalties { get; set; }
        public int HomePenaltyScore { get; set; }
        public int AwayPenaltyScore { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual MatchStatu MatchStatu { get; set; }
        public virtual ICollection<RankingScoreLog> RankingScoreLogs { get; set; }
    }
}
